name: Create Plugin

on: 
  issues: 
    types: 
      - opened
      - reopened
  workflow_dispatch:
    inputs:
      PR:
        description: "PR to download"
        required: true
        default: "9172"
        type: string

jobs:
  createplugin:
    name: Create Plugin
    runs-on: ubuntu-latest
    concurrency:
      group: push-branch-${{ github.ref }}
      cancel-in-progress: false
    permissions: write-all
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Install libraries
        run: |
          python3 -m pip install Pillow
      - name: Create plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.issue.body }}" python3 .github/workflows/python_script.py
      - name: Commit plugin
        run: |
          git config user.name "script" 
          git config user.email "<>"
          rm *
          rm -r .github/*
          rm -r docs/*
          rm -r icons/*
          rm -r installer/*
          rm -r overlays/*
          rm -r resources/*
          rm -r source/*
          rm -r steam/*
          rm -r tests/*
          rm -r utils/*
          git add .
          git commit -m "Generated Plugin"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: false
      - if: contains(github.event.issue.labels.*.name, 'autoclose')
        name: Close Issue
        uses: peter-evans/close-issue@v3
      - name: Zip plugin
        run: |
          zip -r PR.zip PR
      - name: Upload plugins to release
        uses: ncipollo/release-action@v1.11.1
        with:
          tag: latest
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          artifacts: "*.zip"
