name: Create Plugin

on: 
  issues: 
    types: 
      - opened
      - reopened

jobs:
  createplugin:
    name: Create Plugin
    runs-on: ubuntu-latest
    concurrency:
      group: push-branch-${{ github.ref }}
      cancel-in-progress: false
    permissions: write-all
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Install libraries
        run: |
          python3 -m pip install Pillow
      - name: Create plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.issue.body }}" python3 .github/workflows/python_script.py
      - name: Get requested PR
        uses: andstor/file-reader-action@v1
        with:
          path: 'PR_NUMBER'
        id: pr_number
      - name: Zip plugin
        run: |
          PR_NUM="${{ steps.pr_number.outputs.contents }}"
          PR_NUM=$(echo "$PR_NUM" | tr -d '\n' | tr -d '\r')
          echo "Zipping folder: '$PR_NUM'"
          zip -r "PR-$PR_NUM.zip" "$PR_NUM"
      - name: Upload plugins to release
        uses: ncipollo/release-action@v1.11.1
        with:
          tag: latest
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          artifacts: "*.zip"
      - if: contains(github.event.issue.labels.*.name, 'autoclose')
        name: Add Comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            The plugin was generated, so this issue is being automatically closed.
            You can download it on the [release page](https://github.com/TheGiraffe3/PR-to-plugin/releases/tag/latest).
      - if: contains(github.event.issue.labels.*.name, 'autoclose')
        name: Close Issue
        uses: peter-evans/close-issue@v3
