name: Create Plugin

on: 
  issues: 
    types: 
      - opened
      - reopened

jobs:
  createplugin:
    name: Create Plugin
    runs-on: ubuntu-latest
    concurrency:
      group: push-branch-${{ github.ref }}
      cancel-in-progress: false
    permissions: write-all
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Install libraries
        run: |
          python3 -m pip install Pillow
      - name: Create plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.issue.body }}" python3 .github/workflows/python_script.py
      - name: Commit plugin
        run: |
          git config user.name "script" 
          git config user.email "<>"
          git add .
          git commit -m "Generated Plugin"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: false
      - if: contains(github.event.issue.labels.*.name, 'autoclose')
        name: Add Comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue is being automatically closed, since the plugin was generated.
            You can download it on the releases page.
      - if: contains(github.event.issue.labels.*.name, 'autoclose')
        name: Close Issue
        uses: peter-evans/close-issue@v3
      - name: Get requested PR
        uses: andstor/file-reader-action@v1
        with:
          path: 'PR_NUMBER'
        id: pr_number
      - name: Zip plugin
        run: |
          zip -r ${{ steps.pr_number.outputs.contents }}.zip ${{ steps.pr_number.outputs.contents }}
      - name: Upload plugins to release
        uses: ncipollo/release-action@v1.11.1
        with:
          tag: latest
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          artifacts: "*.zip"
